### PR TITLE
update jsch to 0.1.55

### PR DESCRIPTION
**Pull request by culmat**

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Changelog is here: http://www.jcraft.com/jsch/ChangeLog

No security-related changes in the production code, but now there is a warning in CI:

```
java.security.InvalidKeyException: The security strength of SHA-1 digest algorithm is not sufficient for this key size
```

**Comment by jglick** [comment]
I feel I ran into this error recently while migrating some plugin or another to a new core baseline, but at the moment I cannot recall where.

**Comment by batmat** [comment]
Superseded by https://github.com/jenkinsci/jsch-plugin/pull/6/files#diff-600376dffeb79835ede4a0b285078036R84

Can you close this @jeffret-b maybe? Thanks

**Comment by jeffret-b** [comment]
Closing as requested due to completion of superseding change.

**Pull request closed without merging**
